### ISSUE TITLE
small changes needed for linux

### ISSUE THREAD

**Issue by philkerr** [KiboOst/python-devoloDHC#1]
small changes are needed to make it work on linux
- use of path names
- cookies

**Comment by KiboOst** [comment]
Hi,

Would you elaborate ? 
pyDHC actually use os.path to set cookies file.
I have no linux to test, so I will need more info on what does not work, and if you can, how to make it work.

**Comment by philkerr** [comment]
the path should have the format "/&lt;dir&gt;/&lt;subdir&gt;/"
I have commented the load and save lines (self.cookieJar.load and self.cookieJar.save) and the preliminary tests show it stills works. I don't know the function of cookies in pyDHC.
